version: "3"
services:
  ircddbgateway:
    image: ve3lsr/ircddbgateway
    build: .
    restart: always
    ports:
      - 14519:14519
      - 20000:20000/udp
      - 30001-30007:30001-30007/udp
      - 20001-20007:20001-20007/udp
      - 30051-30057:30051-30057/udp
    volumes:
      - ./logs:/var/log/ircddbgateway
      - ./config/ircddbgateway:/etc/ircddbgateway/ircddbgateway:ro

  ircddbgateway_web:
    image: ve3lsr/ircddbgateway_web
    restart: always
    ports:
      - 8180:80
    volumes:
      - ./logs:/var/log/ircddbgateway
      - ./config/ircddbgateway:/etc/ircddbgateway/ircddbgateway:ro
      - ./ircddblocal.php:/var/www/html/ircddblocal.php:ro
